// Code generated by protoc-gen-go. DO NOT EDIT.
// source: funciones.proto

package DistT3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InformanteBroker struct {
	Accion               string   `protobuf:"bytes,1,opt,name=accion,proto3" json:"accion,omitempty"`
	PlanetaAfectado      string   `protobuf:"bytes,2,opt,name=planeta_afectado,json=planetaAfectado,proto3" json:"planeta_afectado,omitempty"`
	CiudadAfectada       string   `protobuf:"bytes,3,opt,name=ciudad_afectada,json=ciudadAfectada,proto3" json:"ciudad_afectada,omitempty"`
	NuevoValor           string   `protobuf:"bytes,4,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InformanteBroker) Reset()         { *m = InformanteBroker{} }
func (m *InformanteBroker) String() string { return proto.CompactTextString(m) }
func (*InformanteBroker) ProtoMessage()    {}
func (*InformanteBroker) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4090d500a5f9b2, []int{0}
}

func (m *InformanteBroker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InformanteBroker.Unmarshal(m, b)
}
func (m *InformanteBroker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InformanteBroker.Marshal(b, m, deterministic)
}
func (m *InformanteBroker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InformanteBroker.Merge(m, src)
}
func (m *InformanteBroker) XXX_Size() int {
	return xxx_messageInfo_InformanteBroker.Size(m)
}
func (m *InformanteBroker) XXX_DiscardUnknown() {
	xxx_messageInfo_InformanteBroker.DiscardUnknown(m)
}

var xxx_messageInfo_InformanteBroker proto.InternalMessageInfo

func (m *InformanteBroker) GetAccion() string {
	if m != nil {
		return m.Accion
	}
	return ""
}

func (m *InformanteBroker) GetPlanetaAfectado() string {
	if m != nil {
		return m.PlanetaAfectado
	}
	return ""
}

func (m *InformanteBroker) GetCiudadAfectada() string {
	if m != nil {
		return m.CiudadAfectada
	}
	return ""
}

func (m *InformanteBroker) GetNuevoValor() string {
	if m != nil {
		return m.NuevoValor
	}
	return ""
}

type BrokerInformante struct {
	Direccion            string   `protobuf:"bytes,1,opt,name=direccion,proto3" json:"direccion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerInformante) Reset()         { *m = BrokerInformante{} }
func (m *BrokerInformante) String() string { return proto.CompactTextString(m) }
func (*BrokerInformante) ProtoMessage()    {}
func (*BrokerInformante) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4090d500a5f9b2, []int{1}
}

func (m *BrokerInformante) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerInformante.Unmarshal(m, b)
}
func (m *BrokerInformante) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerInformante.Marshal(b, m, deterministic)
}
func (m *BrokerInformante) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerInformante.Merge(m, src)
}
func (m *BrokerInformante) XXX_Size() int {
	return xxx_messageInfo_BrokerInformante.Size(m)
}
func (m *BrokerInformante) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerInformante.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerInformante proto.InternalMessageInfo

func (m *BrokerInformante) GetDireccion() string {
	if m != nil {
		return m.Direccion
	}
	return ""
}

// message informante_servidor
// strings accion, planeta_afectado, ciudad_afectada, Nuevo_Valor
type InformanteServidor struct {
	Accion               string   `protobuf:"bytes,1,opt,name=accion,proto3" json:"accion,omitempty"`
	PlanetaAfectado      string   `protobuf:"bytes,2,opt,name=planeta_afectado,json=planetaAfectado,proto3" json:"planeta_afectado,omitempty"`
	CiudadAfectada       string   `protobuf:"bytes,3,opt,name=ciudad_afectada,json=ciudadAfectada,proto3" json:"ciudad_afectada,omitempty"`
	NuevoValor           string   `protobuf:"bytes,4,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InformanteServidor) Reset()         { *m = InformanteServidor{} }
func (m *InformanteServidor) String() string { return proto.CompactTextString(m) }
func (*InformanteServidor) ProtoMessage()    {}
func (*InformanteServidor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4090d500a5f9b2, []int{2}
}

func (m *InformanteServidor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InformanteServidor.Unmarshal(m, b)
}
func (m *InformanteServidor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InformanteServidor.Marshal(b, m, deterministic)
}
func (m *InformanteServidor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InformanteServidor.Merge(m, src)
}
func (m *InformanteServidor) XXX_Size() int {
	return xxx_messageInfo_InformanteServidor.Size(m)
}
func (m *InformanteServidor) XXX_DiscardUnknown() {
	xxx_messageInfo_InformanteServidor.DiscardUnknown(m)
}

var xxx_messageInfo_InformanteServidor proto.InternalMessageInfo

func (m *InformanteServidor) GetAccion() string {
	if m != nil {
		return m.Accion
	}
	return ""
}

func (m *InformanteServidor) GetPlanetaAfectado() string {
	if m != nil {
		return m.PlanetaAfectado
	}
	return ""
}

func (m *InformanteServidor) GetCiudadAfectada() string {
	if m != nil {
		return m.CiudadAfectada
	}
	return ""
}

func (m *InformanteServidor) GetNuevoValor() string {
	if m != nil {
		return m.NuevoValor
	}
	return ""
}

// message servidor_informante
// ints x, y, z
type ServidorInformante struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int32    `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServidorInformante) Reset()         { *m = ServidorInformante{} }
func (m *ServidorInformante) String() string { return proto.CompactTextString(m) }
func (*ServidorInformante) ProtoMessage()    {}
func (*ServidorInformante) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f4090d500a5f9b2, []int{3}
}

func (m *ServidorInformante) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServidorInformante.Unmarshal(m, b)
}
func (m *ServidorInformante) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServidorInformante.Marshal(b, m, deterministic)
}
func (m *ServidorInformante) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServidorInformante.Merge(m, src)
}
func (m *ServidorInformante) XXX_Size() int {
	return xxx_messageInfo_ServidorInformante.Size(m)
}
func (m *ServidorInformante) XXX_DiscardUnknown() {
	xxx_messageInfo_ServidorInformante.DiscardUnknown(m)
}

var xxx_messageInfo_ServidorInformante proto.InternalMessageInfo

func (m *ServidorInformante) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ServidorInformante) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ServidorInformante) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func init() {
	proto.RegisterType((*InformanteBroker)(nil), "grpc.informante_broker")
	proto.RegisterType((*BrokerInformante)(nil), "grpc.broker_informante")
	proto.RegisterType((*InformanteServidor)(nil), "grpc.informante_servidor")
	proto.RegisterType((*ServidorInformante)(nil), "grpc.servidor_informante")
}

func init() { proto.RegisterFile("funciones.proto", fileDescriptor_4f4090d500a5f9b2) }

var fileDescriptor_4f4090d500a5f9b2 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0xd3, 0xef, 0x03, 0x94, 0xab, 0x11, 0x28, 0x89, 0x8e, 0x84, 0x44, 0xc3, 0x46, 0xdd,
	0x0c, 0x51, 0x96, 0x2e, 0xfc, 0x13, 0xe2, 0x03, 0x8c, 0xc6, 0x85, 0x9b, 0xc9, 0xa5, 0xd3, 0xc1,
	0x46, 0x68, 0x49, 0xe9, 0x4c, 0x80, 0xb7, 0xf0, 0x0d, 0x8c, 0x4f, 0x6a, 0x5a, 0x3a, 0x61, 0x92,
	0xf1, 0x01, 0x5c, 0xde, 0x73, 0xcf, 0x6d, 0x7f, 0xb7, 0xa7, 0xd0, 0x4a, 0x33, 0xc9, 0x84, 0x92,
	0x7c, 0x19, 0x2e, 0xb4, 0x32, 0x8a, 0xd6, 0xa6, 0x7a, 0xc1, 0x06, 0x5f, 0x04, 0x3a, 0x42, 0xa6,
	0x4a, 0xcf, 0x51, 0x1a, 0x1e, 0x4f, 0xb4, 0xfa, 0xe0, 0x9a, 0x1e, 0x43, 0x03, 0x99, 0x75, 0x07,
	0xe4, 0x9c, 0x5c, 0x36, 0x23, 0x5f, 0xd1, 0x2b, 0x68, 0x2f, 0x66, 0x28, 0xb9, 0xc1, 0x18, 0x53,
	0xce, 0x0c, 0x26, 0x2a, 0xf8, 0xe7, 0x1c, 0x2d, 0xaf, 0x3f, 0x78, 0x99, 0x5e, 0x40, 0x8b, 0x89,
	0x2c, 0xc1, 0xa4, 0x70, 0x62, 0xf0, 0xdf, 0x39, 0x8f, 0xb6, 0xb2, 0x37, 0x22, 0x3d, 0x83, 0x03,
	0x99, 0xf1, 0x5c, 0xc5, 0x39, 0xce, 0x94, 0x0e, 0x6a, 0xce, 0x04, 0x4e, 0x7a, 0xb5, 0xca, 0xe0,
	0x1a, 0x3a, 0x5b, 0xac, 0x78, 0x07, 0x4a, 0xfb, 0xd0, 0x4c, 0x84, 0xe6, 0x65, 0xc8, 0x9d, 0x30,
	0xf8, 0x26, 0xd0, 0x2d, 0x6d, 0xb5, 0xe4, 0x3a, 0x17, 0x89, 0xfa, 0x63, 0x7b, 0xdd, 0x41, 0xb7,
	0x00, 0x2b, 0x6f, 0x76, 0x08, 0x64, 0xe5, 0xf0, 0xea, 0x11, 0x59, 0xd9, 0x6a, 0xed, 0x50, 0xea,
	0x11, 0x59, 0xdb, 0x6a, 0xe3, 0xae, 0xab, 0x47, 0x64, 0x73, 0xf3, 0x49, 0xa0, 0xfd, 0x54, 0xa4,
	0xfa, 0x6c, 0x8f, 0x62, 0x9c, 0xde, 0xc2, 0x9e, 0x90, 0xa9, 0x0d, 0x92, 0x9e, 0x84, 0x36, 0xe2,
	0xb0, 0x12, 0x6f, 0xcf, 0x37, 0xaa, 0xaf, 0x7a, 0x0f, 0xfb, 0x76, 0xd8, 0x62, 0xd1, 0xd3, 0xca,
	0x74, 0x41, 0xdb, 0xf3, 0xad, 0x5f, 0xe8, 0x1f, 0xfb, 0x6f, 0xbd, 0xa9, 0x30, 0xef, 0xd9, 0x24,
	0x64, 0x6a, 0x3e, 0x1c, 0xa3, 0x46, 0xc6, 0xf8, 0x6c, 0x38, 0x16, 0x4b, 0xf3, 0x32, 0x9a, 0x34,
	0xdc, 0xd7, 0x1b, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x42, 0x25, 0xc8, 0xd1, 0x8d, 0x02, 0x00,
	0x00,
}
